### ISSUE TITLE
Re-add "Choice" prompt.

### ISSUE THREAD

**Issue by dave-irvine** [tj/co-prompt#2]
The "choice" prompt was removed from commander.js as part of:

https://github.com/visionmedia/commander.js/commit/bf5e1f5ec9fb1af23dd873117558575cd01d7415

However, this style of prompt doesn't seem to exist in co-prompt.

Is there a plan to add this back in to co-prompt?

**Comment by tj** [comment]
I think it was too opinionated personally, there's a lotttt of ways to handle choice input, interactive lists etc are much nicer, no reason someone can't publish co-choose though
